//
//  FindDifferenceStr.m
//  LLYAlgorithmDemo
//
//  Created by lly on 2019/4/8.
//  Copyright © 2019 lly. All rights reserved.
//

//389. Find the Difference
//Easy
//
//464
//
//219
//
//Favorite
//
//Share
//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.


#import "FindDifferenceStr.h"

@implementation FindDifferenceStr

- (instancetype)init
{
    self = [super init];
    if (self) {
        
        char diff = [self findDifferenceStr:@"abcd" str2:@"abcde"];
        NSLog(@"diff = %c",diff);
        
    }
    return self;
}

- (char)findDifferenceStr:(NSString *)str1 str2:(NSString *)str2{
    
    char diff = 0;
    
    NSInteger length = MIN(str1.length, str2.length);
    
    for (int i = 0; i < length; i++) {
        
        char c1 = [str1 characterAtIndex:i];
        diff ^= c1;
        
        char c2 = [str2 characterAtIndex:i];
        diff ^= c2;
    }
    
    char c = 0;
    if (str1.length > length) {
        c = [str1 characterAtIndex:length];
    }
    else{
        c = [str2 characterAtIndex:length];
    }
    
    diff ^= c;
    
    return diff;
    
}

@end
